// for (let i = 0; i < data.length; i++) {
//   const id = data[i].querySelectorAll("td")[0].textContent;
//   const customer = data[i].querySelectorAll("td")[1].textContent;
//   const email = data[i].querySelectorAll("td")[2].textContent;
//   const items = data[i].querySelectorAll("td")[3].textContent;
//   const price = data[i].querySelectorAll("td")[4].textContent;
//   const payment = data[i].querySelectorAll("td")[5].textContent;
//   const status = data[i].querySelector(".badge").textContent;
//   const date = data[i].querySelectorAll("td")[7].textContent;

//   item.push({
//     id,
//     customer,
//     email,
//     items,
//     price,
//     payment,
//     status,
//     date,
//   });
// }

export const tbodyorderHistoryData = [
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1047",
    customer: "Bhavesh Markue",
    email: "Bhavesh@example.com",
    items: "8",
    price: "$140",
    payment: "PAID",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1048",
    customer: "mehul Markue",
    email: "mehul@example.com",
    items: "5",
    price: "$100",
    payment: "COD",
    status: "Delivered",
    date: "2021-10-30",
  },
  {
    id: "1049",
    customer: "Ktn Markue",
    email: "ktn@example.com",
    items: "10",
    price: "$280",
    payment: "COD",
    status: "Return",
    date: "2021-10-30",
  },
  {
    id: "1049",
    customer: "Ktn Markue",
    email: "ktn@example.com",
    items: "10",
    price: "$280",
    payment: "COD",
    status: "Return",
    date: "2021-10-30",
  },
];

export const theadOrderHistoryData = [
  { name: "ID", width: "w-[5%]" },
  { name: "Customer", width: "w-[12%]" },
  { name: "Email", width: "w-[18%]" },

  { name: "Items", width: "w-[7%]" },
  { name: "Price", width: "w-[7%]" },
  { name: "Payment", width: "w-[10%]" },
  { name: "Status", width: "w-[12%]" },
  { name: "Date", width: "w-[12%]" },
  { name: "Action", width: "w-[10%]" },
];
